# Generated by Django 2.2 on 2019-05-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190513_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproducts',
            old_name='user_id',
            new_name='product',
        ),
    ]
